const SQRT = Math.sqrt(2)

const ORIENTATION_TO_ORIENTATION_WITHOUT_DIRECTIONALITY_MAPPING = {
	'RIGHT': 'HORIZONTAL',
	'BOTTOM_RIGHT': 'PRINCIPAL_DIAGONAL',
	'BOTTOM': 'VERTICAL',
	'BOTTOM_LEFT': 'MINOR_DIAGONAL',
	'LEFT': 'HORIZONTAL',
	'TOP_LEFT': 'PRINCIPAL_DIAGONAL',
	'TOP': 'VERTICAL',
	'TOP_RIGHT': 'MINOR_DIAGONAL'
}

export {
	SQRT,
	ORIENTATION_TO_ORIENTATION_WITHOUT_DIRECTIONALITY_MAPPING
}